version: '3.7'


services:
    portfolio:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/portfolio
        ports: 
            - 8000:8000
        env_file:
            - .env.dev
        depends_on: 
            - portfolio-db

    portfolio-db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=portfolio
            - POSTGRES_PASSWORD=portfolio
            - POSTGRES_DB=portfolio_dev

volumes: 
    postgres_data: