version: '3.7'


services:
    nginx:
        build: ./nginx
        volumes: 
            - static_volume:/home/app/portfolio/staticfiles
        ports:
            - 1337:80
        depends_on:
            - portfolio

    portfolio:
        build:
            context: .
            dockerfile: Dockerfile.digitalO.prod
        command: gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/portfolio/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env.digitalO.prod
        depends_on: 
            - portfolio-db

    portfolio-db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - ./.env.digitalO.prod.db
 
volumes: 
    postgres_data:
    static_volume: