version: "3.7"

services:
    portfolio:
        image: "${WEB_IMAGE}"
        command: gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/media
        ports:
            - 8000:8000
        env_file: .env
        depends_on: 
            - portfolio-db

    portfolio-db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - .env.db

    nginx-proxy:
        container_name: nginx-proxy
        image: "${NGINX_IMAGE}"
        restart: always
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/media
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
            - 443:443
        depends_on:
            - portfolio

    nginx-proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
        env_file: 
            - .env.companion  # created in Dockerfile.do.prod and 'scp'-ed
        depends_on: 
            - nginx-proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
