version: '3.7'


services:
    portfolio:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/portfolio
        ports: 
            - 8000:8000
        env_file:
            - .env.dev