version: "3.7"

services:
    portfolio:
        image: "${WEB_IMAGE}"
        command: gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/media
        ports:
            - 8000:8000
        env_file: .env
    nginx:
        image: "${NGINX_IMAGE}"
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/media
        ports:
            - 80:80
        depends_on:
            - portfolio

volumes:
    static_volume:
    media_volume:
